---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ _deploy_packages }}"

- name: Clone repository
  git:
    repo: "{{ deploy_git_repo }}"
    dest: "{{ deploy_dest }}"
    version: "{{ deploy_version }}"
    key_file: "{{ deploy_ssh_key }}"
    accept_hostkey: true
    ssh_opts: "-o StrictHostKeyChecking=no"
    force: yes

- name: Set config <core.fileMode> for repository
  git_config:
    name: core.fileMode
    value: false
    scope: local
    repo: "{{ deploy_dest }}"

- name: Install composer packages
  composer:
    command: install
    working_dir: "{{ deploy_composer_path | dirname }}"
    no_dev: "{{ 'yes' if deploy_env == 'prod' else 'no' }}"
  when: deploy_composer_path is defined

- name: Install npm packages
  npm:
    path: "{{ deploy_npm_path | dirname }}"
  when: deploy_npm_path is defined

- name: Include deploy hook
  include_tasks: "{{ deploy_hook }}"
  when: deploy_hook is defined