---
- name: Include deploy start hook
  include_tasks: "{{ deploy_start_hook }}"
  when: deploy_start_hook is defined

- name: Check if repository is already cloned
  find:
    paths: "{{ deploy_dest }}"
  register: _output

- name: Clone repository
  git:
    repo: "{{ deploy_git_repo }}"
    dest: "{{ deploy_dest }}"
    version: "{{ deploy_version | default(omit) }}"
    key_file: "{{ deploy_ssh_key | default(omit) }}"
    accept_hostkey: true
    ssh_opts: "-o StrictHostKeyChecking=no"
    force: yes
  when: (deploy_override | default('no')) or _output.matched == 0

- name: Set config <core.fileMode> for repository
  git_config:
    name: core.fileMode
    value: "false"
    scope: local
    repo: "{{ deploy_dest }}"

- name: Install composer packages
  composer:
    command: install
    working_dir: "{{ deploy_composer_path | dirname }}"
    no_dev: "{{ 'yes' if deploy_env == 'prod' else 'no' }}"
  when: deploy_composer_path is defined

# Can't use NPM module because it's unreliable
# @see: https://github.com/ansible/ansible/issues/29234
# @see: https://github.com/ansible/ansible/pull/63296

# - name: Install npm packages
#   npm:
#     path: "{{ deploy_npm_path | dirname }}"
#     ci: "{{ deploy_npm_ci | default('no') }}"
#     production: "{{ 'yes' if deploy_env == 'prod' else 'no' }}"
#   when: deploy_npm_path is defined

- name: Install npm packages
  shell: >
    cd {{ deploy_npm_path | dirname }};
    npm {{ 'ci' if deploy_npm_ci is defined and deploy_npm_ci == true else 'install' }}
    {{ '--production' if deploy_env == 'prod' else '' }}
  register: _output
  changed_when: "'added' in _output.stdout or 'updated' in _output.stdout"

- name: Include deploy finish hook
  include_tasks: "{{ deploy_finish_hook }}"
  when: deploy_finish_hook is defined