---
- name: Include deploy start hook
  include_tasks: "{{ deploy_start_hook }}"
  when: deploy_start_hook is defined

- name: Install packages
  apt:
    name: "{{ _deploy_packages }}"

- name: Clone repository
  git:
    repo: "{{ deploy_git_repo }}"
    dest: "{{ deploy_dest }}"
    version: "{{ deploy_version | default(omit) }}"
    key_file: "{{ deploy_ssh_key | default(omit) }}"
    accept_hostkey: true
    ssh_opts: "-o StrictHostKeyChecking=no"
    force: "{{ deploy_override | default('no') }}"

- name: Set config <core.fileMode> for repository
  git_config:
    name: core.fileMode
    value: false
    scope: local
    repo: "{{ deploy_dest }}"

- name: Install composer packages
  composer:
    command: install
    working_dir: "{{ deploy_composer_path | dirname }}"
    no_dev: "{{ 'yes' if deploy_env == 'prod' else 'no' }}"
  when: _php_role is defined and deploy_composer_path is defined

- name: Install npm packages
  npm:
    path: "{{ deploy_npm_path | dirname }}"
  when: _nodejs_role is defined and deploy_npm_path is defined

- name: Include deploy finish hook
  include_tasks: "{{ deploy_finish_hook }}"
  when: deploy_finish_hook is defined