# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box       = "bento/ubuntu-16.04"
    config.vm.hostname  = "ansible-test.local"
    config.vm.network "private_network", ip: "192.168.13.37"
    config.vm.synced_folder "../", "/etc/ansible/roles/test"

    config.vm.provider "virtualbox" do |vbox|
        vbox.memory = 2048
        vbox.cpus   = 2
    end

    config.vm.provision "shell", path: "Vagrantboot"

    config.vm.provision "ansible_local" do |ansible|
        ansible.inventory_path    = "inventory"
        ansible.playbook          = "test.yml"
        ansible.limit             = "localhost"
    end
end
